repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml
        args: ["--allow-multiple-documents"]
      - id: check-json
        exclude: tsconfig.*\.json|package-lock\.json|biome\.jsonc
      - id: check-toml
      - id: check-xml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
        args: ["--maxkb=1000"]
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: detect-private-key
      - id: mixed-line-ending
        args: ["--fix=lf"]
  - repo: local
    hooks:
      - id: biome
        name: biome
        entry: npx biome check --write
        language: system
        files: \.(js|ts|jsx|tsx)$
        exclude: ^(package\.json|package-lock\.json|database\.rules\.json)$
        pass_filenames: true
      - id: prettier
        name: prettier
        entry: npx prettier --write
        language: system
        types_or: [yaml, markdown, html]
      - id: eslint
        name: eslint
        entry: bash -c 'npx --no-install eslint --fix "$@"' --
        language: system
        files: ^src/.*\.(js|ts|jsx|tsx)$
