repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml
      - id: check-json
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: local
    hooks:
      - id: biome
        name: biome
        entry: npx biome check --write
        language: system
        files: \.(js|ts|jsx|tsx)$
        exclude: ^(package\.json|package-lock\.json)$
        pass_filenames: true
      - id: prettier
        name: prettier
        entry: npx prettier --write
        language: system
        types_or: [yaml, markdown, html]
      - id: eslint
        name: eslint
        entry: bash -c 'npx --no-install eslint --fix "$@"' --
        language: system
        files: ^src/.*\.(js|ts|jsx|tsx)$
