onlyBuiltDependencies:
  - esbuild
minimumReleaseAge: 1440
minimumReleaseAgeStrict: true
minimumReleaseAgeIgnoreMissingTime: false
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@0.2.8
  vitest: 4.1.11
  vite-plus: 0.3.0
overrides:
  vite: "catalog:"
  vitest: "catalog:"
  "gaxios@6>uuid": "11.1.1"
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
allowBuilds:
  "@firebase/util": false
  "@sentry/cli": true
  "@swc/core": true
  esbuild: true
  fallow: true
  protobufjs: false
  re2: false
  unrs-resolver: true
  workerd: false
