export const SUBSCRIBE_TO_BLUEPRINT  = 'SUBSCRIBE_TO_BLUEPRINT';
export const SUBSCRIBED_TO_BLUEPRINT = 'SUBSCRIBED_TO_BLUEPRINT';
export const RECEIVED_BLUEPRINT      = 'RECEIVED_BLUEPRINT';
export const BLUEPRINT_FAILED        = 'BLUEPRINT_FAILED';

export const SUBSCRIBE_TO_SUMMARIES  = 'SUBSCRIBE_TO_SUMMARIES';
export const SUBSCRIBED_TO_SUMMARIES = 'SUBSCRIBED_TO_SUMMARIES';
export const RECEIVED_SUMMARIES      = 'RECEIVED_SUMMARIES';
export const SUMMARIES_READY         = 'SUMMARIES_READY';
export const SUMMARIES_LAST_PAGE     = 'SUMMARIES_LAST_PAGE';
export const SUMMARIES_FAILED        = 'SUMMARIES_FAILED';

export const GO_TO_PREVIOUS_SUMMARIES    = 'GO_TO_PREVIOUS_SUMMARIES';
export const GO_TO_NEXT_SUMMARIES        = 'GO_TO_NEXT_SUMMARIES';
export const GO_TO_FIRST_SUMMARIES       = 'GO_TO_FIRST_SUMMARIES';

export const SAVE_PREVIOUS_SUMMARIES    = 'SAVE_PREVIOUS_SUMMARIES';
export const SAVE_NEXT_SUMMARIES        = 'SAVE_NEXT_SUMMARIES';
export const SAVE_FIRST_SUMMARIES       = 'SAVE_FIRST_SUMMARIES';

export const WENT_TO_PREVIOUS_SUMMARIES    = 'WENT_TO_PREVIOUS_SUMMARIES';
export const WENT_TO_NEXT_SUMMARIES        = 'WENT_TO_NEXT_SUMMARIES';
export const WENT_TO_FIRST_SUMMARIES       = 'WENT_TO_FIRST_SUMMARIES';

export const RECIEVED_PREVIOUS_SUMMARIES = 'RECIEVED_PREVIOUS_SUMMARIES';
export const RECIEVED_NEXT_SUMMARIES     = 'RECIEVED_NEXT_SUMMARIES';
export const RECIEVED_FIRST_SUMMARIES    = 'RECIEVED_FIRST_SUMMARIES';

export const SUBSCRIBE_TO_MY_FAVORITES  = 'SUBSCRIBE_TO_MY_FAVORITES';
export const SUBSCRIBED_TO_MY_FAVORITES = 'SUBSCRIBED_TO_MY_FAVORITES';
export const RECEIVED_MY_FAVORITES      = 'RECEIVED_MY_FAVORITES';
export const MY_FAVORITES_READY         = 'MY_FAVORITES_READY';
export const MY_FAVORITES_LAST_PAGE     = 'MY_FAVORITES_LAST_PAGE';
export const MY_FAVORITES_FAILED        = 'MY_FAVORITES_FAILED';

export const GO_TO_PREVIOUS_MY_FAVORITES    = 'GO_TO_PREVIOUS_MY_FAVORITES';
export const GO_TO_NEXT_MY_FAVORITES        = 'GO_TO_NEXT_MY_FAVORITES';
export const GO_TO_FIRST_MY_FAVORITES       = 'GO_TO_FIRST_MY_FAVORITES';

export const SAVE_PREVIOUS_MY_FAVORITES    = 'SAVE_PREVIOUS_MY_FAVORITES';
export const SAVE_NEXT_MY_FAVORITES        = 'SAVE_NEXT_MY_FAVORITES';
export const SAVE_FIRST_MY_FAVORITES       = 'SAVE_FIRST_MY_FAVORITES';

export const WENT_TO_PREVIOUS_MY_FAVORITES    = 'WENT_TO_PREVIOUS_MY_FAVORITES';
export const WENT_TO_NEXT_MY_FAVORITES        = 'WENT_TO_NEXT_MY_FAVORITES';
export const WENT_TO_FIRST_MY_FAVORITES       = 'WENT_TO_FIRST_MY_FAVORITES';

export const RECIEVED_PREVIOUS_MY_FAVORITES = 'RECIEVED_PREVIOUS_MY_FAVORITES';
export const RECIEVED_NEXT_MY_FAVORITES     = 'RECIEVED_NEXT_MY_FAVORITES';
export const RECIEVED_FIRST_MY_FAVORITES    = 'RECIEVED_FIRST_MY_FAVORITES';

export const GO_TO_PREVIOUS_ALL_FAVORITES    = 'GO_TO_PREVIOUS_ALL_FAVORITES';
export const GO_TO_NEXT_ALL_FAVORITES        = 'GO_TO_NEXT_ALL_FAVORITES';
export const GO_TO_FIRST_ALL_FAVORITES       = 'GO_TO_FIRST_ALL_FAVORITES';

export const SAVE_PREVIOUS_ALL_FAVORITES    = 'SAVE_PREVIOUS_ALL_FAVORITES';
export const SAVE_NEXT_ALL_FAVORITES        = 'SAVE_NEXT_ALL_FAVORITES';
export const SAVE_FIRST_ALL_FAVORITES       = 'SAVE_FIRST_ALL_FAVORITES';

export const WENT_TO_PREVIOUS_ALL_FAVORITES    = 'WENT_TO_PREVIOUS_ALL_FAVORITES';
export const WENT_TO_NEXT_ALL_FAVORITES        = 'WENT_TO_NEXT_ALL_FAVORITES';
export const WENT_TO_FIRST_ALL_FAVORITES       = 'WENT_TO_FIRST_ALL_FAVORITES';

export const RECIEVED_PREVIOUS_ALL_FAVORITES = 'RECIEVED_PREVIOUS_ALL_FAVORITES';
export const RECIEVED_NEXT_ALL_FAVORITES     = 'RECIEVED_NEXT_ALL_FAVORITES';
export const RECIEVED_FIRST_ALL_FAVORITES    = 'RECIEVED_FIRST_ALL_FAVORITES';

export const SUBSCRIBE_TO_ALL_FAVORITES      = 'SUBSCRIBE_TO_ALL_FAVORITES';
export const SUBSCRIBED_TO_ALL_FAVORITES     = 'SUBSCRIBED_TO_ALL_FAVORITES';
export const RECEIVED_ALL_FAVORITES          = 'RECEIVED_ALL_FAVORITES';
export const ALL_FAVORITES_READY             = 'ALL_FAVORITES_READY';
export const ALL_FAVORITES_LAST_PAGE         = 'ALL_FAVORITES_LAST_PAGE';
export const ALL_FAVORITES_FAILED            = 'ALL_FAVORITES_FAILED';

export const SUBSCRIBE_TO_TAGS  = 'SUBSCRIBE_TO_TAGS';
export const SUBSCRIBED_TO_TAGS = 'SUBSCRIBED_TO_TAGS';
export const RECEIVED_TAGS      = 'RECEIVED_TAGS';

// TODO: Where is this used?
export const SUBSCRIBE_TO_USER                       = 'SUBSCRIBE_TO_USER';
export const SUBSCRIBE_TO_USER_DISPLAY_NAME          = 'SUBSCRIBE_TO_USER_DISPLAY_NAME';
export const SUBSCRIBED_TO_USER_DISPLAY_NAME         = 'SUBSCRIBED_TO_USER_DISPLAY_NAME';
export const SUBSCRIBE_TO_USER_BLUEPRINTS_SUMMARIES  = 'SUBSCRIBE_TO_USER_BLUEPRINTS_SUMMARIES';
export const SUBSCRIBED_TO_USER_BLUEPRINTS_SUMMARIES = 'SUBSCRIBED_TO_USER_BLUEPRINTS_SUMMARIES';
export const RECEIVED_USER_DISPLAY_NAME              = 'RECEIVED_USER_DISPLAY_NAME';
export const RECEIVED_USER_BLUEPRINTS_SUMMARIES      = 'RECEIVED_USER_BLUEPRINTS_SUMMARIES';
export const RECEIVED_USER_BLUEPRINTS_KEYS           = 'RECEIVED_USER_BLUEPRINTS_KEYS';

export const AUTH_STATE_CHANGED  = 'AUTH_STATE_CHANGED';
export const EDITED_DISPLAY_NAME = 'EDITED_DISPLAY_NAME';

export const SUBSCRIBE_TO_MODERATORS  = 'SUBSCRIBE_TO_MODERATORS';
export const SUBSCRIBED_TO_MODERATORS = 'SUBSCRIBED_TO_MODERATORS';
export const RECEIVED_MODERATORS      = 'RECEIVED_MODERATORS';

export const FILTER_ON_TAGS  = 'FILTER_ON_TAGS';
export const SAVE_FILTER_ON_TAGS  = 'SAVE_FILTER_ON_TAGS';
export const FILTERED_ON_TAGS  = 'FILTERED_ON_TAGS';

export const FILTER_ON_TITLE = 'FILTER_ON_TITLE';
export const SAVE_FILTER_ON_TITLE = 'SAVE_FILTER_ON_TITLE';
export const FILTERED_ON_TITLE = 'FILTERED_ON_TITLE';

export const FETCHING_MY_AUTHORED_BLUEPRINT_KEYS = 'FETCHING_MY_AUTHORED_BLUEPRINT_KEYS';
export const RECEIVED_MY_AUTHORED_BLUEPRINT_KEYS = 'RECEIVED_MY_AUTHORED_BLUEPRINT_KEYS';
export const MY_AUTHORED_BLUEPRINT_KEYS_FAILED = 'MY_AUTHORED_BLUEPRINT_KEYS_FAILED';

export const FETCHING_MY_FAVORITE_BLUEPRINT_KEYS = 'FETCHING_MY_FAVORITE_BLUEPRINT_KEYS';
export const RECEIVED_MY_FAVORITE_BLUEPRINT_KEYS = 'RECEIVED_MY_FAVORITE_BLUEPRINT_KEYS';
export const MY_FAVORITE_BLUEPRINT_KEYS_FAILED = 'MY_FAVORITE_BLUEPRINT_KEYS_FAILED';

export const FETCHING_MY_ENTITLEMENTS = 'FETCHING_MY_ENTITLEMENTS';
export const RECEIVED_MY_ENTITLEMENTS = 'RECEIVED_MY_ENTITLEMENTS';
export const MY_ENTITLEMENTS_FAILED = 'MY_ENTITLEMENTS_FAILED';
