export const SUBSCRIBE_TO_BLUEPRINT = 'SUBSCRIBE_TO_BLUEPRINT';
export const SUBSCRIBED_TO_BLUEPRINT = 'SUBSCRIBED_TO_BLUEPRINT';
export const RECEIVED_BLUEPRINT = 'RECEIVED_BLUEPRINT';

export const SUBSCRIBE_TO_SUMMARIES = 'SUBSCRIBE_TO_SUMMARIES';
export const SUBSCRIBED_TO_SUMMARIES = 'SUBSCRIBED_TO_SUMMARIES';
export const RECEIVED_SUMMARIES = 'RECEIVED_SUMMARIES';

export const SUBSCRIBE_TO_TAGS = 'SUBSCRIBE_TO_TAGS';
export const SUBSCRIBED_TO_TAGS = 'SUBSCRIBED_TO_TAGS';
export const RECEIVED_TAGS = 'RECEIVED_TAGS';

export const SUBSCRIBE_TO_TAG = 'SUBSCRIBE_TO_TAG';
export const SUBSCRIBED_TO_TAG = 'SUBSCRIBED_TO_TAG';
export const RECEIVED_TAG = 'RECEIVED_TAG';

export const SUBSCRIBE_TO_USER = 'SUBSCRIBE_TO_USER';
export const SUBSCRIBED_TO_USER_DISPLAY_NAME = 'SUBSCRIBED_TO_USER_DISPLAY_NAME';
export const SUBSCRIBED_TO_USER_BLUEPRINTS = 'SUBSCRIBED_TO_USER_BLUEPRINTS';
export const RECEIVED_USER_DISPLAY_NAME = 'RECEIVED_USER_DISPLAY_NAME';
export const RECEIVED_USER_BLUEPRINTS = 'RECEIVED_USER_BLUEPRINTS';

export const AUTH_STATE_CHANGED = 'AUTH_STATE_CHANGED';

export const SUBSCRIBED_TO_MY_FAVORITES = 'SUBSCRIBED_TO_MY_FAVORITES';
export const RECEIVED_MY_FAVORITES = 'RECEIVED_MY_FAVORITES';

export const SUBSCRIBE_TO_MODERATORS = 'SUBSCRIBE_TO_MODERATORS';
export const SUBSCRIBED_TO_MODERATORS = 'SUBSCRIBED_TO_MODERATORS';
export const RECEIVED_MODERATORS = 'RECEIVED_MODERATORS';

export const FILTER_ON_TAGS = 'FILTER_ON_TAGS';
export const FILTER_ON_TITLE = 'FILTER_ON_TITLE';

