import {forbidExtraProps} from 'airbnb-prop-types';
import PropTypes          from 'prop-types';

/**
 * Auto-generated by com.klass.generator.react.prop.type.PropTypeSourceCodeProjectionVisitor
 * at 2019-04-14T13:04:32.858Z
 */
const BlueprintKeyProjection = PropTypes.shape(forbidExtraProps({
	key: PropTypes.string.isRequired,
}));

export default BlueprintKeyProjection;
