import {forbidExtraProps}      from 'airbnb-prop-types';
import PropTypes               from 'prop-types';
import CommentProjection       from './CommentProjection';
import DisqusCommentProjection from './DisqusCommentProjection';
import ImgurImageProjection    from './ImgurImageProjection';

/**
 * Auto-generated by com.klass.generator.react.prop.type.PropTypeSourceCodeProjectionVisitor
 * at 2019-04-14T13:04:32.858Z
 */
const BlueprintProjection = PropTypes.shape(forbidExtraProps({
	key                : PropTypes.string.isRequired,
	version            : PropTypes.shape(forbidExtraProps({
		number: PropTypes.number.isRequired,
	})).isRequired,
	systemFrom         : PropTypes.string.isRequired,
	systemTo           : PropTypes.string,
	createdOn          : PropTypes.string.isRequired,
	lastUpdatedById    : PropTypes.string.isRequired,
	title              : PropTypes.string.isRequired,
	descriptionMarkdown: PropTypes.string.isRequired,
	numberOfUpvotes    : PropTypes.number.isRequired,
	numberOfDownvotes  : PropTypes.number.isRequired,
	author             : PropTypes.shape(forbidExtraProps({
		userId     : PropTypes.string.isRequired,
		displayName: PropTypes.string.isRequired,
	})).isRequired,
	imgurImage         : ImgurImageProjection.isRequired,
	tags               : PropTypes.arrayOf(PropTypes.shape(forbidExtraProps({
		tag: PropTypes.shape(forbidExtraProps({
			category: PropTypes.string.isRequired,
			name    : PropTypes.string.isRequired,
		})).isRequired,
	})).isRequired).isRequired,
	disqusComments     : PropTypes.arrayOf(DisqusCommentProjection.isRequired).isRequired,
	comments           : PropTypes.arrayOf(CommentProjection.isRequired).isRequired,
	blueprintString    : PropTypes.shape(forbidExtraProps({
		blueprintString: PropTypes.string.isRequired,
	})),
}));

export default BlueprintProjection;
