import {forbidExtraProps} from 'airbnb-prop-types';
import PropTypes          from 'prop-types';

/**
 * Auto-generated by com.klass.generator.react.prop.type.PropTypeSourceCodeProjectionVisitor
 * at 2019-04-14T13:04:32.858Z
 */
const CommentProjection = PropTypes.shape(forbidExtraProps({
	id   : PropTypes.number.isRequired,
	text : PropTypes.string.isRequired,
	votes: PropTypes.arrayOf(PropTypes.shape(forbidExtraProps({
		direction: PropTypes.string.isRequired,
	})).isRequired).isRequired,
}));

CommentProjection.replies = PropTypes.arrayOf(CommentProjection.isRequired).isRequired;
export default CommentProjection;
