import {forbidExtraProps} from 'airbnb-prop-types';
import PropTypes          from 'prop-types';

/**
 * Auto-generated by com.klass.generator.react.prop.type.PropTypeSourceCodeProjectionVisitor
 * at 2019-04-14T13:04:32.858Z
 */

const projectionBody                  = {
	id       : PropTypes.number.isRequired,
	text     : PropTypes.string.isRequired,
	deleted  : PropTypes.bool.isRequired,
	createdOn: PropTypes.string,
	author   : PropTypes.shape(forbidExtraProps({
		name    : PropTypes.string.isRequired,
		username: PropTypes.string.isRequired,
	})).isRequired,
};
const DisqusCommentProjection = PropTypes.shape(forbidExtraProps(projectionBody));

projectionBody.replies = PropTypes.arrayOf(DisqusCommentProjection.isRequired).isRequired;

export default DisqusCommentProjection;
