import {forbidExtraProps} from 'airbnb-prop-types';
import PropTypes          from 'prop-types';

/**
 * Auto-generated by com.klass.generator.react.prop.type.PropTypeSourceCodeProjectionVisitor
 * at 2019-04-14T13:04:32.858Z
 */
const ImgurImageProjection = PropTypes.shape(forbidExtraProps({
	imgurId   : PropTypes.string.isRequired,
	imgurType : PropTypes.string.isRequired,
	deleteHash: PropTypes.string,
	height    : PropTypes.number.isRequired,
	width     : PropTypes.number.isRequired,
}));

export default ImgurImageProjection;
