name: Integration

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "22.x"
          cache: "npm"

      - run: npm ci --ignore-engines --ignore-platform --ignore-scripts --legacy-peer-deps
      - run: npm run lint

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "22.x"
          cache: "npm"

      - run: npm ci --ignore-engines --ignore-platform --ignore-scripts --legacy-peer-deps
      - run: npm run route:generate
      - run: npm test

  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - uses: pre-commit/action@v3.0.1

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "22.x"
          cache: "npm"

      - run: npm ci --ignore-engines --ignore-platform --ignore-scripts --legacy-peer-deps
      - run: npm run build
